---
- job:
    name: repoxplorer-config-check
    parent: base
    description: Verification of the repoxplorer config syntax
    run: playbooks/syntax-check.yaml
    nodeset:
      nodes:
        - name: test-node
          label: runc-centos

- project:
    check:
      jobs:
        - repoxplorer-config-check
    gate:
      jobs:
        - repoxplorer-config-check
    post:
      jobs:
        - noop
