project-templates:
  Red Hat QE Security:
    branches:
    - master
    gitweb: http://github.com/redhat-qe-security/%(name)s/commit/%%(sha)s
    uri: http://github.com/redhat-qe-security/%(name)s
projects:
  Red Hat QE Security:
    description: Red Hat Quality Engineering Secruity Team
    repos:
      certgen:
        branches:
        - master
        template: Red Hat QE Security
      interoperability:
        branches:
        - master
        template: Red Hat QE Security
      keyfile-corpus:
        branches:
        - master
        template: Red Hat QE Security
      pcl-analyzer:
        branches:
        - master
        template: Red Hat QE Security
